{"version":1,"title":"WARNING in io_try_cancel_userdata (2)","id":"64f92c7d92a87b540571307f5eae74dbf2262444","fix-commits":[{"title":"io_uring: fail cancellation for EXITING tasks","link":"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=617a89484debcd4e7999796d693cf0b77d2519de","hash":"617a89484debcd4e7999796d693cf0b77d2519de","repo":"git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git","branch":"master"}],"discussions":["https://groups.google.com/d/msgid/syzkaller-bugs/00000000000080c60105d1a7d4b5%40google.com"],"crashes":[{"title":"WARNING in io_try_cancel_userdata","kernel-config":"/text?tag=KernelConfig\u0026x=152798d01fe6adcd","kernel-source-git":"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?id=40c93d7fff6ff05c1c4c9f9c01a067eac6a791b1","kernel-source-commit":"40c93d7fff6ff05c1c4c9f9c01a067eac6a791b1","syzkaller-git":"https://github.com/google/syzkaller/commits/4eb20a4ea7cf78f84d015cefa160aff806c35ec7","syzkaller-commit":"4eb20a4ea7cf78f84d015cefa160aff806c35ec7","crash-report-link":"/text?tag=CrashReport\u0026x=17cc9126b00000"}]}